### PR TITLE
update why

### PR DESCRIPTION
**Pull request by JoshKeenMurr**
I pray this is right and that my boss doesn't yell at me again ;-; (for her mistake)

### CODE REVIEW

**Review by ChloeSheasby — COMMENTED** [review]
Looks good except needs more why besides paid a lot?

**Comment by JoshKeenMurr** [comment]
@ChloeSheasby I appreciate the thought but I disagree. Short and to the point

**Review by grace-hopp — COMMENTED** [review]
Good code. I feel you really went in-depth about why you should be a computer science major.

**Comment by ChloeSheasby** [comment]
Well I want a good grade...

**Pull request merged**
