### PR TITLE
Put all html files in one folder and updated hrefs

### PR DESCRIPTION
**Pull request by ChloeSheasby**
All pages are now in a folder called scripts. Updated hrefs with this new path and deleted any unnecessary comments.

### CODE REVIEW

**Comment by ChloeSheasby** [comment]
Don't merge this yet. Need to fix hrefs first.

**Comment by ChloeSheasby** [comment]
Okay, this is ready to be merged. I forgot to update some of the hrefs on the index page.

**Review by grace-hopp — APPROVED** [review]
perfect. looks good!

**Review by JoshKeenMurr — APPROVED** [review]
awesome

**Comment by ChloeSheasby** [comment]
This should be good to merge now. Let me know what you guys think.

**Comment by JoshKeenMurr** [comment]
Seems pog to me

**Pull request merged**
